 CREATE TABLE BBUser(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
Username VARCHAR(50) NOT NULL, 
RetiredFlag BIT NOT NULL,
UNIQUE(Username));
CREATE TABLE BBSource(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
SourceType CHAR(2) NOT NULL, 
SourceAddress VARCHAR(75) NOT NULL, 
Name VARCHAR(50) NOT NULL, 
IsActive BIT NOT NULL,
UNIQUE(SourceAddress));
CREATE TABLE BBPriority(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
Description VARCHAR(50) NOT NULL
);
CREATE TABLE BBPermissions(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
Description VARCHAR(50) NOT NULL, 
IsModerator BIT NOT NULL
);
CREATE TABLE BBInfluence(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
Description CHAR(50) NOT NULL, 
WithinInfluenceId INT NULL
);
CREATE TABLE BBArticleBill(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
Questionable BIT NOT NULL, 
Verified BIT NOT NULL, 
QuestionableCount INT NULL, 
InfluenceId INT NOT NULL, 
SourceId INT NOT NULL, 
PriorityId INT NOT NULL, 
Title VARCHAR(75) NOT NULL, 
IsBill BIT NOT NULL, 
IsSpotlight BIT NOT NULL, 
Updated DATETIME NOT NULL,
UNIQUE(Title),
FOREIGN KEY (InfluenceId) REFERENCES BBInfluence(Id),
FOREIGN KEY (SourceId) REFERENCES BBSource(Id),
FOREIGN KEY (PriorityId) REFERENCES BBPriority(Id)
);
CREATE TABLE BBTags(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(30) NOT NULL,
IsRequest BIT NOT NULL,
InfluenceId INT NULL, 
ArticleId INT NOT NULL,
UNIQUE(Name),
FOREIGN KEY (InfluenceId) REFERENCES BBInfluence(Id),
FOREIGN KEY (ArticleId) REFERENCES BBArticleBill(Id)
);
CREATE TABLE BBArticleTags(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TagId INT NOT NULL,
ArticleId INT NOT NULL,
FOREIGN KEY (TagId) REFERENCES BBTags(Id),
FOREIGN KEY (ArticleId) REFERENCES BBArticleBill(Id)
);